frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  stage: ${opt:stage, 'dev'}
  mobilizeAmerica:
    dev: ${ssm:MOBILIZE_AMERICA_DEV}
    staging: ${ssm:MOBILIZE_AMERICA_PROD}
    prod: ${ssm:MOBILIZE_AMERICA_PROD}
  mongo:
    dev: ${ssm:TOOLS_SHARED_MONGO_DEV~true}
    staging: ${ssm:TOOLS_SHARED_MONGO_PROD~true}
    prod: ${ssm:TOOLS_SHARED_MONGO_PROD~true}
  customDomain:
    domainName: api.elizabethwarren.codes
    basePath: ${self:custom.stage}-events-v2
    stage: ${self:custom.stage}
    createRoute53Record: true
  serverless-offline:
    host: 0.0.0.0
    port: 3001
  logForwarding:
    destinationARN: ${cf:lambda-papertrail-prod.ForwarderLambdaArn}

service: events-api-v2

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    MONGODB_URI: ${self:custom.mongo.${self:custom.stage}}

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-log-forwarding

functions:
  api:
    handler: src/handler.router
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
  importEvents:
    timeout: 600  # Timeout after 10 minutes
    handler: src/handler.importEvents
    events:
      - schedule: rate(5 minutes)

package:
  exclude:
    - data/**
